rule build_report:
    input:
        qc="results/{sample}/qc/bakta_input_check.json",
        bakta="results/{sample}/bakta/{sample}.metadata.json",
        antismash="results/{sample}/summary/antismash.bgc.tsv",
        gecco="results/{sample}/summary/gecco.bgc.tsv",
        deepbgc="results/{sample}/summary/deepbgc.bgc.tsv",
        arts="results/{sample}/summary/arts.hits.tsv",
        dbcan="results/{sample}/summary/dbcan.cgc.tsv",
        cluster_maps="results/{sample}/summary/cluster_gene_maps.tsv",
        cluster_genes="results/{sample}/summary/cluster_genes.tsv",
        consensus="results/{sample}/summary/consensus_bgcs.tsv",
        evidence="results/{sample}/summary/region_evidence.tsv",
        overlap="results/{sample}/summary/tool_overlap.tsv",
        provenance="results/{sample}/provenance.json"
    output:
        "results/{sample}/report/{sample}.html"
    conda:
        "../envs/report.yaml"
    script:
        "../scripts/build_report.py"
